import { Inter } from "next/font/google";
import "./globals.css";
import Layout from '@/components/Layout';
import { TitleProvider } from '@/context/title';
const inter = Inter({ subsets: ["latin"] });
import TokenProvider from "@/context/TokenContext";

export const metadata = {
  title: "EaseTick",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TokenProvider>
          <TitleProvider>
            <Layout>
              {children}
            </Layout>
          </TitleProvider>
        </TokenProvider>
      </body>
    </html>
  );
}

