import { Inter } from "next/font/google";
import "./globals.css";
import Layout from '@/components/Layout';
import { TitleProvider } from '@/context/title';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EaseTick",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <TitleProvider>
          <Layout>
            {children}
          </Layout>
        </TitleProvider>
      </body>
    </html>
  );
}
